WebApp3/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp3.Models
{
    public class Tag
    {
        public int TagId { get; set; }
        public string TagTitle { get; set; }
        public string TagDescription { get; set; }
        public List<FanficTag> FanficsTags { get; set; } = new List<FanficTag>(); 
    }
}

WebApp3/ViewModels/CreateTagViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp3.ViewModels
{
    public class CreateTagViewModel
    {
        public string TagTitle { get; set; }
        public string TagDescription { get; set; }
        public DateTime DateTimePublish { get; set; } = DateTime.Now;
        public List<SelectListItem> Tags { get; set; }
        public string[] SelectedTags { get; set; }
    }
}

WebApp3/ViewModels/TagViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp3.ViewModels
{
    public class TagViewModel
    {
        public int TagId { get; set; }
        public string TagTitle { get; set; }
        public string TagDescription { get; set; }
    }
}

WebApp3/Controllers/TagController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp3.Areas.Identity.DbContext;
using WebApp3.Helpers;
using WebApp3.Interfaces;
using WebApp3.Models;
using WebApp3.ViewModels;

namespace WebApp3.Controllers
{
    public class TagController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private ApplicationUserDbContext _applicationUserDbContext;
        private IMapper _mapper;
        public TagController(IUnitOfWork unitOfWork, IMapper mapper, ApplicationUserDbContext applicationUserDbContext)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _applicationUserDbContext = applicationUserDbContext;
        }
        // GET: TagController
        public async Task<IActionResult> TagList(int page = 1)
        {
            int pageSize = 12; // количество элементов на странице
            IQueryable<Tag> tag = _unitOfWork.Tag.GetTagsAsync();
            int countElement = await tag.CountAsync();
            var items = await tag.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
            PaginationPageViewModel paginationPageViewModel = new PaginationPageViewModel(countElement, page, pageSize);
            FanficTagViewModel fanficTagViewModel = new FanficTagViewModel()
            {
                PaginationPageViewModel = paginationPageViewModel,
                Tags = items
            };
         
                return View(fanficTagViewModel);
         

        }

        // GET: TagController/Details/5
     

        // GET: TagController/Create
        public ActionResult CreateTag()
        {
            return View();
        }

        // POST: TagController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTag(CreateTagViewModel createTagViewModel)
        {
            try
            {
                IEnumerable<Tag> tagsList = await _unitOfWork.Tag.GetAllAsync();
                var model = _mapper.Map<Tag>(createTagViewModel);
                if (ModelState.IsValid)
                {
                    if (String.IsNullOrEmpty(model.TagTitle) || String.IsNullOrEmpty(model.TagDescription))
                    {
                        ModelState.AddModelError("", "");
                        return Json(new
                            {isValid = false, textMessage = "Значение не может быть пустым",  html = HelperForJSON.RenderRazorViewToString(this, "CreateTag", createTagViewModel)});
                    }

                    foreach (var tagLists in tagsList)
                    {
                        if (model.TagTitle == tagLists.TagTitle)
                        {
                            ModelState.AddModelError("", "");
                            return Json(new
                                { isValid = false, textMessage= "Недопустимы названия одинаковых меток", html = HelperForJSON.RenderRazorViewToString(this, "CreateTag", createTagViewModel) });
                        }
                    }
                    
                 await _unitOfWork.Tag.InsertAsync(model);
                 await  _unitOfWork.SaveAsync();

                }
                 return Json(new {isValid = true });
            }
            catch
            {
                return View();
            }
        }

        //// GET: TagController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: TagController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: TagController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: TagController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

WebApp3/Views/Tag/CreateTag.cshtml
@model WebApp3.ViewModels.CreateTagViewModel

@{
    Layout = null;
}


        <form asp-action="CreateTag" id="createtag-content" onsubmit="return jQueryAjaxPost(this, 'Отлично', 'Вы создали метку!', 'success')">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Название метки</label>
                <input asp-for="TagTitle" class="form-control" />
                <span asp-validation-for="TagTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Описание</label>
                <textarea asp-for="TagDescription" class="form-control" style="height: 150px"></textarea>
                <span asp-validation-for="TagDescription" class="text-danger"></span>
            </div>
            <div class="form-group delete">
                <input onclick="closePopUp(this)" class="btn btn-danger" value="Назад" />
                <input type="submit" value="Создать" class="btn btn-danger" />
            </div>
        </form>
 

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<style>
    label{
        color: #231954;
    }
    .delete{
        display: flex;
        padding: 10px;
    }
    input.btn{
        margin: 10px;
        }
</style>

WebApp3/Views/Tag/TagList.cshtml
@model WebApp3.ViewModels.FanficTagViewModel
@{
    ViewData["Title"] = "Список меток";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="container">
        @if (!User.Identity.IsAuthenticated)
        {
            <p>
                <a data-toggle="modal" onclick="showInPopup('@Url.Action("Login", "Home", null, Context.Request.Scheme)', 'Авторизация')">Добавить метку</a>
            </p>
        }
        @if (User.Identity.IsAuthenticated)
        {
            <p>
                <a data-toggle="modal" onclick="showInPopup('@Url.Action("CreateTag", "Tag", null, Context.Request.Scheme)', 'Создание новой метки')">Добавить метку</a>
            </p>
        }
        <div class="tag-list">
            <div class="top-header">
                <h2>Метки</h2>
            </div>
            <form>
                <div class="input-group">
                    <input class="form-control" id="searchTag" placeholder="Поиск содержимого метки">
                </div>
            </form>
            <div class="col-sm-12">
                <div class="row tags-row" id="tableTag">
                    @foreach (var tags in Model.Tags)
                    {
                        <div class="col-sm-4 about">
                            <div class="tag-name">
                                <form method="get">
                                    <a class="tagtitle" asp-controller="Fanfic" asp-action="FanficList" asp-route-idTag="@tags.TagId">@tags.TagTitle</a>
                                </form>
                                <sup>x @tags.FanficsTags.Select(ps => ps.Fanfic.FanficId).Count()</sup>
                            </div>
                            <div class="tag-description">
                                @tags.TagDescription
                            </div>
                        </div>
                    }
                </div>
                <nav aria-label="Page navigation example">
                    <form asp-action="TagList" method="get">
                        <div class="page-number">
                            <div>
                                <input type="number" name="page" class="form-control" value="@Model.PaginationPageViewModel.NumberPage" min="1" max="@Model.PaginationPageViewModel.TotalPage" />
                            </div>
                            <div class="number-last">
                                <b>из @Model.PaginationPageViewModel.TotalPage</b>
                            </div>
                            <div>
                                <button type="submit" class="btn btn-outline-secondary btn-sm">Перейти</button>
                            </div>
                        </div>
                    </form>
                    <ul class="pagination justify-content-center">
                        @if (Model.PaginationPageViewModel.HasPreviousPage)
                        {
                            <li class="page-item">
                                <a class="page-link" asp-action="TagList" asp-route-page="@(Model.PaginationPageViewModel.NumberPage - 1)" tabindex="-1">&lt; Назад</a>
                            </li>
                        }

                        @if (Model.PaginationPageViewModel.HasNextPage)
                        {
                            <li class="page-item">
                                <a class="page-link" asp-action="TagList" asp-route-page="@(Model.PaginationPageViewModel.NumberPage + 1)">Далее &gt;</a>
                            </li>
                        }
                    </ul>
                </nav>
            </div>
        </div>
    </div>


<style>
    body {
        color: white;
    }
    .subscribe{
          color: white;
      
      }
    .page-link{
            margin-left: 15px !important;
        }
    div.page-number{
        color: white;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 10px;
    }
    div.number-last{
        margin-left: 10px;
        margin-right: 10px;
    }
    .tag-name.hide {
        display: none;
    }

    a:hover {
        cursor: pointer;
    }

    .top-header {
        border-bottom: 1px solid #eee;
    }

    .about {
        border-bottom: 1px dotted #eee;
    }

    .tag-list .tags-row {
        padding-top: 10px;
        padding-bottom: 10px;
    }

    .tag-name {
        margin-bottom: 5px;
        color: #888;
        font-size: 14px;
    }

    a.tag {
        background-color: lightblue;
        padding: 5px 7px;
    }

    a.tag:hover {
        background-color: rgb(141, 182, 195);
        text-decoration: none;
    }

    .tag-description {
        color: #888;
    }

    .about {
        padding: 15px;
    }

    .tag-name {
        margin-bottom: 15px;
    }
</style>
<script>
    $(document).ready(function () {
        $("#searchTag").on("keyup",
            function () {
                var dataSearch = $(this).val().toLowerCase();
                $("#tableTag .about").each(function () {
                    var stringData = $(this).text().toLowerCase();
                    if (stringData.indexOf(dataSearch) === -1) {
                        $(this).hide();
                    } else {
                        $(this).show();
                    }
                });
            });
    });
</script>