WebApp3/Models/Chapter.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp3.Models
{
    public class Chapter
    {
        public int ChapterId { get; set; }
        public string ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
        public int FanficId { get; set; }
        public Fanfic Fanfics { get; set; }
        public string NameChapter { get; set; }
        public string TextChapter { get; set; }
        public DateTime DateTimePuplish { get; set; } = DateTime.Now;
    }
}

WebApp3/Controllers/ChapterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp3.Areas.Identity.DbContext;
using WebApp3.Interfaces;
using WebApp3.Models;
using WebApp3.ViewModels;

namespace WebApp3.Controllers
{
    public class ChapterController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationUserDbContext _a;
        public ChapterController(IUnitOfWork unitOfWork, IMapper mapper, UserManager<ApplicationUser> userManager, ApplicationUserDbContext a)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
            _a = a;
        }
        // GET: ChapterController
        public ActionResult Index(int id)
        {
            return View(new CreateChapterViewModel()
            {
                Chapters = _a.Chapters.Include(n => n.Fanfics)
                    .ToList()
                    .Where(n => n.FanficId == id)
            });
        }

        // GET: ChapterController/Details/5
        public ActionResult Details(int id)
        {
            var chapter = _unitOfWork.Chapter.GetChapterById(id);
            var viewmodel = new CreateChapterViewModel
            {
                NameChapter = chapter.NameChapter, TextChapter = chapter.TextChapter
            };
            return View(viewmodel);
        }

        // GET: ChapterController/Create
        [ActionName("Create")]
        public async Task<IActionResult> CreateChapter(int id)
        {
            var fanfic = await _unitOfWork.Fanfic.GetByIdAsync(id);
            var viewmodel = new CreateChapterViewModel()
            {
                Fanfics = fanfic
            };
            return View(viewmodel);
        }

        // POST: ChapterController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id,CreateChapterViewModel chapterViewModel)
        {
            try
            {
                var fanfic = await _unitOfWork.Fanfic.GetByIdAsync(id);
                var user = fanfic.ApplicationUser;
                var chapter = new Chapter()
                {
                    NameChapter = chapterViewModel.NameChapter,
                    TextChapter = chapterViewModel.TextChapter,
                    Fanfics = fanfic,
                    ApplicationUser = user
                };
                _unitOfWork.Chapter.AddChapter(chapter);
                await _unitOfWork.SaveAsync();
                return RedirectToAction("FanficList", "Fanfic");
            }
            catch
            {
                return View("Create");
            }
        }

        // GET: ChapterController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = _unitOfWork.Chapter.GetChapterById(id);
            var viewmodel = new EditChapter()
            {
                NameChapter = model.NameChapter,
                TextChapter = model.TextChapter
            };
            return View(viewmodel);
        }

        // POST: ChapterController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ChapterController/Delete/5
        public ActionResult Delete()
        {
            return View();
        }

        // POST: ChapterController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp3/Views/Chapter/Create.cshtml
@model WebApp3.ViewModels.CreateChapterViewModel

@{
    ViewData["Title"] = "Создание главы";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Создание новой главы</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label>Название главы</label>
                <input asp-for="NameChapter" class="form-control" />
                <span asp-validation-for="NameChapter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Сожержимое</label>
                <textarea asp-for="TextChapter" class="form-control" style="height: 450px"></textarea>
                <span asp-validation-for="TextChapter" class="text-danger"></span>
            </div>
            <div class="form-group create">
              
                <input type="submit" value="Создать главу" asp-route-id="@Model.Fanfics.FanficId" class="btn btn-danger"/>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<style>
 label{
     color: white;
     }
 .create{
     display: flex;
     padding: 10px;
     justify-content: center;
 }
 input.btn{
     margin: 10px;
 }
  </style>

WebApp3/Views/Chapter/Details.cshtml
@model WebApp3.ViewModels.CreateChapterViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="aaa">
    <h1> @Html.DisplayFor(model => model.NameChapter)</h1>
@Html.ActionLink("Edit", "Edit", new {  id = Model.ChapterId  }) |
    <a asp-action="Index">Back to List</a>

    <div class="container">
        <div class="col-md-12">
            @Html.DisplayFor(model => model.TextChapter)
        </div>
    </div>
</div>
<style>
    *{
        color: wheat;
    }
</style>

WebApp3/Views/Chapter/Edit.cshtml
@model WebApp3.ViewModels.EditChapter

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>EditChapter</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NameChapter" class="control-label"></label>
                <input asp-for="NameChapter" class="form-control" />
                <span asp-validation-for="NameChapter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TextChapter" class="control-label"></label>
                <textarea style="height: 350px" asp-for="TextChapter" class="form-control"></textarea>
                <span asp-validation-for="TextChapter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<style>
    * {
        color: wheat;
    }
</style>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp3/Views/Chapter/Index.cshtml
@model WebApp3.ViewModels.CreateChapterViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<div class="container">
    @foreach (var item in Model.Chapters)
    {
        <div class="body">
        <div class="chapter">
            <a asp-controller="Chapter" asp-action="Details" asp-route-id="@item.ChapterId" class="hrefchapter">@Html.DisplayFor(modelItem => item.NameChapter)</a>
        </div>
        <div class="time">
            <small> @Html.DisplayFor(modelItem => item.DateTimePuplish)</small>
        </div>
    </div>
    }
</div>

<style>
    div .container, a.hrefchapter, a.hrefchapter:hover {
        display: block;
        background-color: teal;
        padding: 7px;
        color: wheat;
        border-radius: 5px;
    }
    div .body{
        margin: 20px;
        border: 2px solid wheat;
    }
    div .chapter {
        font-size: 28px;
    }
    div .right{
        float: right!important;
        font-size: 28px;
        padding: 7px;
        color: wheat;
        }
    div .time{
        padding: 7px;
        color: wheat;
        }
    </style>